name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature_description
    attributes:
      label: Feature request description
      description: Please explain your feature request and if it is related to a problem
    validations:
      required: true
  - type: textarea
    id: potential_solution
    attributes:
      label: Suggest potential solution
      description: Please explain if you can suggest any potential solution
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Have you considered any alternatives?
      description: Please explain what alternatives you have tried.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Please add any context to this feature request
    validations:
      required: false
